name: structural_directives
description: Structural directives example
version: 0.0.1

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  angular: ^5.3.1
  angular_components: 0.13.0+1
  angular_forms: ^2.1.2

dev_dependencies:
  build_runner: ^1.7.0
  build_test: ^0.10.8
  build_web_compilers: ^2.4.0
