source "http://rubygems.org"
gem 'autoprefixer-rails'
gem 'bootstrap-sass'
gem 'font-awesome-sass'
gem 'jekyll'
gem 'jekyll-assets', '>=2.3.2', '<3.0.0'
gem 'jekyll-toc'
gem 'kramdown'
gem 'nokogiri'
gem 'sass'
gem 'uglifier'